### ISSUE TITLE
Raspbian user name

### ISSUE THREAD

**Issue by wires** [debian-pi/general#1]
Was just reading this,

https://github.com/debian-pi/general/wiki/Making-the-case-for-a-raspbian-organization

Are you aware of github [name squatting policy](https://help.github.com/articles/name-squatting-policy/)? I think the account applies, which means you could contact github and ask for the account to be released, then you can setup a new organisation using the name.

(I think rasbian org. would be a good idea, do collaborate with raspbian/debian devs when applicable, raspbian rocks! And thanks for your work on raspbian-ua-netinst)

**Comment by diederikdehaas** [comment]
I have asked GitHub about it and although you can't see any public activity, the account is used though. 
But we have been using this username/organization for quite a while now, so I won't change it now.
I'd better update/remove that wiki page :wink:
