### ISSUE TITLE
Failing to bind port 8332 on boot

### ISSUE THREAD

**Issue by levino** [debian-pi/general#2]
Hey there,

I am pretty sure this is not the right place but I have an issue with raspbian and setting up a script to run bitcoind on startup.

I use the `bitcoind.service` startup script from here: https://github.com/bitcoin/bitcoin/blob/master/doc/init.md

When I have the raspberry pi running, I can start the service easily with `systemctl start bitcoind`.

However on boot, I get the error that binding port 8332 fails which means that the rpc interface of bitcoind is not available. Binding 8333 works on boot, so bitcoind is running fine but I cannot connect to it. So I have to kill the process, start it again and voila, I can access it.

So what to take of this? Where can I get help on this issue? I am happy to move my question where it belongs but would really appreciate a hint to the correct forum or whatever.

**Comment by goranche** [comment]
hm... that's most likely not a raspbian issue, no...

It's a question for the bitcoin project community (or maintainers team)... although it might could be a question for the systemd team :thought_balloon: 

I'd start with the bitcoin project, though, maybe anyone else has had a similar issue before?
